### ISSUE TITLE
Theme selection menu is over tabs

### ISSUE THREAD

**Issue by dreamflasher** [sn-extensions/secure-spreadsheets#3]
The theme selection menu is placed over the tabs of the sheets and the right scroll button, so that one can't properly switch between tabs. If this is not on your end (not sure about the themes) but again part of the spreadsheet software: What's the repo of the spreadsheet software, so that I can open bug reports there?

**Comment by mobitar** [comment]
The theme selection in place for spreadsheets is our own overlay. We have an [outstanding bounty](https://github.com/standardnotes/bounties/issues/23) of converting spreadsheets to use our own themes, at which point, that overlay will no longer be required. The spreadsheet itself software is made Progress Telerik.

**Comment by DreamFlasher** [comment]
Could you move the overlay meanwhile to the top right because there is nothing there (in the first level menu bar line)?

Ah so it's this? https://demos.telerik.com/kendo-ui/spreadsheet/index -- I highly appreciate that you invested a significant amount of money to purchase such a great component. It's a bit unfortunate though, that they're not open source themselves so that one can't create bug reports/feature requests.

**Comment by mobitar** [comment]
Yeah, we'll be at their mercy for updates. As for making our own changes, the next change will be compatibility with our own themes so we can get rid of that switcher altogether. There was some work on this by @bryvin but not sure how far he got.

**Comment by bryvin** [comment]
I have a pretty much working setup (though it's messy, I just went through the inspector and overrode a bunch of css classes), for some reason the scrollbar thing has never worked for me locally. Even right now testing on a local web app, the scrollbar for any extension (folders for example) is the default OS scrollbar. But it works 100% fine in the production version. I'll push what I have as a PR to possibly be reviewed.

![screenshot from 2019-02-06 19-32-14](https://user-images.githubusercontent.com/5969300/52383116-f4390b80-2a45-11e9-9cf3-1a42561e3e5a.png)

**Comment by alandooz** [comment]
I think this issue is resolved.
